# Generated by Django 3.0.8 on 2020-10-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='conceptName')),
                ('description', models.TextField(verbose_name='conceptDescription')),
            ],
        ),
    ]
