# Generated by Django 3.0.8 on 2020-10-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0002_concepts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120, verbose_name='questionTitle')),
                ('questionDescription', models.TextField(blank=True, verbose_name='conceptDescription')),
                ('RightAnswer', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=30)),
                ('NeutralAnswer', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=30)),
                ('WrongAnswer', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=30)),
            ],
        ),
    ]
