# Generated by Django 3.0.8 on 2020-10-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slag', '0003_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question',
        ),
        migrations.AddField(
            model_name='questions',
            name='answerOption1',
            field=models.TextField(blank=True, verbose_name='answer1'),
        ),
        migrations.AddField(
            model_name='questions',
            name='answerOption2',
            field=models.TextField(blank=True, verbose_name='answer2'),
        ),
        migrations.AddField(
            model_name='questions',
            name='answerOption3',
            field=models.TextField(blank=True, verbose_name='answer3'),
        ),
    ]
